services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Senha123!
      POSTGRES_DB: kronos
    ports:
      - "54321:5432"
    networks:
      - kronos_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=Host=postgres;Database=kronos;Username=postgres;Password=Senha123!
    ports:
      - "8006:8080"
    networks:
      - kronos_network
    depends_on:
      postgres:
        condition: service_healthy
        
networks:
  kronos_network:
    driver: bridge