services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Senha123!
      POSTGRES_DB: kronos
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=Host=172.17.0.1;Database=titan;Username=postgres;Password=Senha123!
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        URL_API: http://localhost:5001/api/v1
    ports:
      - "8001:80"
    depends_on:
      - server